import Config

port_available? = fn port ->
  case :gen_tcp.listen(port, [:binary, active: false, ip: {127, 0, 0, 1}, reuseaddr: true]) do
    {:ok, socket} ->
      :gen_tcp.close(socket)
      true

    {:error, _reason} ->
      false
  end
end

pick_free_port = fn preferred_port, fallback_ports, excluded_ports ->
  Enum.find([preferred_port | fallback_ports], fn port ->
    port not in excluded_ports and port_available?.(port)
  end) || preferred_port
end

resolve_port = fn env_vars, default_port, fallback_ports, excluded_ports ->
  configured_port =
    env_vars
    |> Enum.map(&System.get_env/1)
    |> Enum.find(&(&1 not in [nil, ""]))
    |> case do
      nil -> default_port
      value -> String.to_integer(value)
    end

  candidate_ports =
    if configured_port == default_port do
      fallback_ports
    else
      Enum.to_list((configured_port + 1)..(configured_port + 10)) ++ fallback_ports
    end

  resolved_port = pick_free_port.(configured_port, candidate_ports, excluded_ports)

  if resolved_port != configured_port do
    IO.warn(
      "#{Enum.join(env_vars, "/")} requested port #{configured_port}, but it is unavailable in dev; falling back to #{resolved_port}"
    )
  end

  resolved_port
end

live_debugger_port =
  resolve_port.(["LIVE_DEBUGGER_PORT"], 4007, Enum.to_list(4008..4015), [])

config :live_debugger,
  api_settings_storage: LemmingsOs.LiveDebuggerSettingsStorage,
  port: live_debugger_port

port =
  resolve_port.(["PORT", "MIX_PORT"], 4000, Enum.to_list(4001..4010), [live_debugger_port])

# Configure your database
config :lemmings_os, LemmingsOs.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "lemmings_os_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :lemmings_os, LemmingsOsWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: port],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "/Ily+so3ISdGbbab2WHDR6brJAhvF+M1PYmLP2qIP2ZY9I2imPQq8N42A0ciZdC/",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:lemmings_os, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:lemmings_os, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :lemmings_os, LemmingsOsWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/lemmings_os_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :lemmings_os, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
